image: python:3.9-slim-bullseye

pipelines:
  branches:
    '**':
      - step:
          name: Run local tests
          script:
            - pip3 install -r tests/requirements-3.9.txt
            - py.test image/tests.py
